apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: Configmap-demo
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux-9