apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    purpose: annotations-demo
annotations:
  description: "this is created for annotations"
  jenkins: "http://www.roboshop/cart/items"
spec:
  containers:
  - name: nginx
    image: nginx