apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels:
    project: roboshop
    environment: dev
    purpose: resource-demo
spec:
  containers:
  - name: nginx
    image: nginx
  resources:
    requests:
      memory: "126MI"
      cpu: "500m"
    limits:
      memory: "256MI"
      cpu: "1000m"