apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    project: roboshop
    purpose: env-vars
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: sham
      value: "jawa 4227"
    - name: sham1
      value: "punch 0174" 