apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-demo
  labels:
    project: roboshop
    purpose: configmap-demo
spec:
data:
  - name: sham
    value: "son of krishna"
  - name: sham vamshi
    value: "son of swaroopa"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    Envfrom:
      ConfigMapRef:
      - name: configmap-demo